# Read https://github.com/Ezard/semantic-prs/blob/master/README.md#configuration for more information on the available configuration options.

# Validate the PR title, and ignore all commit messages
titleOnly: true

types:
  - feat
  - fix
  - test
  - docs
  - refactor
  - chore
  - dependabot

scopes:
  - BCD
  - BCG
  - BCC